services:
  # Backend API Service
  - type: web
    name: habit-streak-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false  # Set this in Render dashboard
      - key: FRONTEND_URL
        value: https://habit-streak-frontend.onrender.com
    healthCheckPath: /
    autoDeploy: true

  # Frontend Static Site
  - type: web
    name: habit-streak-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build:prod
    staticPublishPath: frontend/dist/habit-streak-frontend
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    routes:
      - type: rewrite
        source: /**
        destination: /index.html
